### PR TITLE
proposal [breaking changes]

### LINKED ISSUE #5: [question] why this is only related to vue?
why this appears to work only in vue rather than every ES6 class?

### LINKED ISSUE #7: support static methods on ES6 classes
related https://github.com/enkot/catch-decorator/issues/5

### PR DESCRIPTION
**Pull request by k1r0s**
upgraded, catch decorator can be stacked, support multiple promise chaining, conditional errors, handle is defined on implementation

fix #7 
fix #5

### CODE REVIEW

**Comment by k1r0s** [comment]
this change doesn't include readme changes

**Comment by enkot** [comment]
@k1r0s Sorry for delay, was busy. Idea is great :), but I don't really like implementation with dependencies (this lib used in real projects). I like InversifyJS, and kaop is cool for modularity. But you replaced all code in this commit 🙂, so maybe it will be better for you to create separate catch decorator with your vision:)

**Comment by k1r0s** [comment]
yeah, I just dropped because I reaized that it was completely different no because Im angry or something :)))

**Comment by k1r0s** [comment]
I replaced all code bcoz if you want to stack decorators on top of each other you need all to be compatible and kaop is a decorator framework. No prob bro, gl

**Pull request closed without merging**
